### ISSUE TITLE
Tinode.isRelativeURL is not a function

### ISSUE THREAD

**Issue by young310** [tinode/webapp#101]
**Describe the bug**
Could not download file using web app interface.

**To Reproduce**
1. Go to chat window
2. Click on the file to download
3. The progress bar will be stuck

**Expected behavior**
File should be downloaded successfully.

**Screenshots**
![Screen Shot 2022-09-21 at 23 38 44](https://user-images.githubusercontent.com/8056293/191548847-aadcd20b-adf0-4e5d-845a-fd9900cc3b13.png)

**Environment (please complete the following information):**
 - OS: Both Windows and MacOS
 - Browser: Both Chrome and Safari
 - TinodeWeb Version v0.20.0-rc1
 - TinodeServer Version v0.20.0-rc1

**Console log**
[15:35:15.492] out: {"note":{"topic":"usrMwpdl99BJbA","what":"read","seq":14}} 
react-dom.production.min.js:56 Uncaught TypeError: Tinode.isRelativeURL is not a function
    at De.default.download (tinode.prod.js:1:40637)
    at zs.downloadFile (attachment.jsx:29:16)
    at s (attachment.jsx:72:14)
    at Object.vi (react-dom.production.min.js:202:330)
    at ui (react-dom.production.min.js:32:27)
    at xi (react-dom.production.min.js:32:81)
    at zg (react-dom.production.min.js:55:403)
    at rg (react-dom.production.min.js:56:317)
    at react-dom.production.min.js:66:168
    at react-dom.production.min.js:240:292

**Additional context**
There is no error message in server side.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/tinode-js/commit/b0e036bdb48db940d2e5cd21797f8111e9439a19
